### ISSUE TITLE
JobFlowStatus and JobFlowStatusStep in need of a reboot after underlying API changes

### ISSUE THREAD

**Issue by rslifka** [rslifka/elasticity#105]
`JobFlow` depends on the now-deprecated (and deleted) `Elasticity::EMR#describe_job_flows` to obtain both the job flow status and the status of the individual steps in a job flow.  The new EMR API breaks these up in to two separate calls.

Dependent methods are as follows and likely some transitive dependencies as well.

```
JobFlow.from_jobflow_id
JobFlow#status
JobFlow#retry_check
```

**Comment by robert2d** [comment]
:+1:

**Comment by rslifka** [comment]
As of 1146b2c78012288d4fda04adfb9f53d2e6573db7, `JobFlow#status` has been removed in favour of `JobFlow#cluster_status` and `JobFlow#cluster_step_status`
