### ISSUE TITLE
Add support for EMR 4.x

### ISSUE THREAD

**Issue by fblundun** [rslifka/elasticity#121]
Hi @rslifka ,

EMR release 4.0.0 introduced a breaking API change: "AMI version" has been replaced by "release label" ([source](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-differences.html#emr-release-label)).

Setting the AMI version to 4.0.0 with Elasticity doesn't work results in the following error:

```
ArgumentError (AWS EMR API Error (ValidationException): The supplied ami version is invalid.):
    /home/vagrant/.rvm/gems/jruby-1.7.19/gems/elasticity-6.0.5/lib/elasticity/aws_session.rb:33:in `submit'
    /home/vagrant/.rvm/gems/jruby-1.7.19/gems/elasticity-6.0.5/lib/elasticity/emr.rb:302:in `run_job_flow'
    /home/vagrant/.rvm/gems/jruby-1.7.19/gems/elasticity-6.0.5/lib/elasticity/job_flow.rb:141:in `run'
    /vagrant/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:393:in `run'
```

It would be great to get support for the release label API!

cc @alexanderdean

**Comment by robert2d** [comment]
Hi @fblundun, there is an open pull request for this [here](https://github.com/rslifka/elasticity/pull/120) im hoping to merge this very soon, if you wanted to give it a go try using that branch and if you're happy with it i'll merge it into the main trunk.

**Comment by fblundun** [comment]
Thanks @rslifka! We don't need to start using it just yet, but when we do we will try that branch and keep you informed.

**Comment by fblundun** [comment]
Hi @robert2d ,

I've just started testing with the latest revision (7491254a76e44cdecc976d037564c35a196e447d) of your PR. The only change I have made to my code is to replace

```ruby
jobflow.ami_version = '3.7.0'
```

with

```ruby
jobflow.release_label = 'emr-4.1.0'
```

The first step of my job is an S3DistCp, which fails with an elapsed time of 0 seconds. I've downloaded the cluster logs but can't find any useful information in them. Do you have any idea what might be going wrong here?

**Comment by fblundun** [comment]
@robert2d I was able to get the S3DistCp step working by changing the S3DistCpStep class to use the path `/usr/share/aws/emr/s3-dist-cp/lib/s3-dist-cp.jar` instead of `/home/hadoop/lib/emr-s3distcp-1.0.jar`, based on [this thread](https://forums.aws.amazon.com/thread.jspa?threadID=204633).

**Comment by alexanderdean** [comment]
Thanks @fblundun - sounds like we probably need a new ticket in Elasticity called something like "Select S3DistCp path based on AMI/release version"

**Comment by robert2d** [comment]
Yea that sounds reasonable and would site right [here](https://github.com/rslifka/elasticity/blob/master/lib/elasticity/s3distcp_step.rb#L6)
