### ISSUE TITLE
Add launch_hbase support

### ISSUE THREAD

**Issue by alexanderdean** [rslifka/elasticity#49]
We have our first use case at Snowplow where we need to fire up HBase on the EMR cluster.[1]

From reading the documentation section "To launch an HBase cluster using the API" it looks like launching the cluster involves adding a new bootstrap action and startup job step:

```
Steps.member.1.Name=InstallHBase&
Steps.member.1.ActionOnFailure=CONTINUE&
Steps.member.1.bootstrapAction.ScriptbootstrapAction=s3://us-east-1.elasticmapreduce/bootstrap-actions/setup-hbase&
Steps.member.1.Name=StartHBase&
Steps.member.1.ActionOnFailure=CANCEL_AND_WAIT&
Steps.member.1.HadoopJarStep.Jar=/home/hadoop/lib/hbase-0.92.0.jar&
Steps.member.1.HadoopJarStep.Args.member.1=emr.hbase.backup.Main&
Steps.member.1.HadoopJarStep.Args.member.2=--start-master&
```

Would it be possible to add first class support for starting HBase into Elasticity?

[1] http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-hbase-launch.html

**Comment by rslifka** [comment]
Hey @alexanderdean I know it's been a while.  Would this still be valuable to add?  I'm not familiar with HBase so I'd need your help to make sure this flies before release.

**Comment by alexanderdean** [comment]
Hey @rslifka - I think it's still a valid feature. The only job we run which uses HBase is on a pretty version of Snowplow&Elasticity, but we can give it a try!
