### ISSUE TITLE
Add support for tagging jobflows

### ISSUE THREAD

**Issue by slpsys** [rslifka/elasticity#59]
Amazon added the ability to [tag jobflows](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-tags.html) with arbitrary strings, which is extremely useful in the scenario that you're running lots of jobs all the time, as it lets you examine your billing more granularly. Would be great to get add this as a feature, otherwise I can attempt to put together a pull request.

**Comment by kmcrawford** [comment]
How's this going?

**Comment by rslifka** [comment]
It's not at the moment.  Happy to review pull requests!

**Comment by rslifka** [comment]
Folding in to the big Elasticity 6.0.  Amazon's been busy :)  (also @slpsys just ping me on the Rands Slack if you need something!)

**Comment by rslifka** [comment]
Closing - pointing to separate issues now for inclusion in 6.0: #89 and #90.

**Comment by slpsys** [comment]
Somehow just seeing the new issues now. :heart_eyes_cat:
