### ISSUE TITLE
Add support for service_role

### ISSUE THREAD

**Issue by alexanderdean** [rslifka/elasticity#81]
As per boto: https://github.com/boto/boto/blob/develop/boto/emr/connection.py#L577

Driving reason for this is that on 6th April [AWS changed](http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-iam-roles-creatingroles.html) how EMR jobflows need to be authenticated:

> If you created your first cluster before April 6, 2015, IAM roles are not mandatory. However, we 
> recommend that you specify IAM roles for your cluster as a best practice.

Here's my understanding of support currently:

| aws cli        | boto & API        | elasticity    | defaults* |
|----------------|-------------|---------------|---------------|
| `--ec2-attributes InstanceProfile=x`             | `JobFlowRole` | `job_flow_role` | `"EMR_EC2_DefaultRole"` |
| `--service-role=x` | `ServiceRole` | #81           | `"EMR_DefaultRole"` |

\* Created using `$ aws emr create-default-roles`

**Comment by alexanderdean** [comment]
@rslifka it would be amazing if this were available in a 4.0.5 as well as 5.x, given the J/Ruby changes in 5.x :palm_tree:

Let me know if you want me to submit a PR!

**Comment by falschparker82** [comment]
+1, this is bugging us too right now - can we help?

**Comment by rslifka** [comment]
Done for both `4.0.5` and `5.0.1` as of ba6e37dbaa3a0db4399fc33745d91ddd07c2a864.  Keeping a 4.x branch around, just in case.

**Comment by alexanderdean** [comment]
Thanks @rslifka !
