### ISSUE TITLE
InstanceProfile is required for creating cluster

### ISSUE THREAD

**Issue by c4ssio** [rslifka/elasticity#84]
Hi guys, just getting started with this gem (v5.0.2, using ruby ) and I've followed the instructions to get the cloudburst custom jar going. I updated the aws key and secret key to my own, updated the OUTPUT_BUCKET to a bucket on my s3, but when i do jobflow.run, I get one of these:

```
ArgumentError:
from /Users/cpaesleme/.rvm/gems/ruby-2.1.5/gems/elasticity-5.0.2/lib/elasticity/aws_session.rb:36:in `rescue in submit'
```

...so, a blank error string, maybe there's an issue with the xml output.

if I monkeypatch the code to get the actual e.http_output, I see:

```
{"__type":"ValidationException","message":"InstanceProfile is required for creating cluster"}
```

I'm going thru the code to see if there's a way to specify the EMR_EC2_DefaultRole for the InstanceProfile, but it seems like something no one else is having trouble with so maybe I'm missing something obvious. Is there an environment variable or something I'm supposed to set to get this working?

**Comment by rslifka** [comment]
Please see https://github.com/rslifka/elasticity/issues/81 :)

**Comment by c4ssio** [comment]
woop woop! We're rolling. Thanks!

**Comment by rslifka** [comment]
Sure thing, any time!  Let me know if you have any feature requests!

**Comment by fbelghait** [comment]
Am having the same problem,  I have done done the following:
I am trying to do a simple job in EMR, I have done the following steps
1. with "aws configure" I have entered the credential information and the region information
2. with " aws emr create-default-roles" to use the default role I ave created to access the S3 bucket
3. ./elastic-mapreduce --create --stream \
--input s3://.........../input \
--output s3://........./output \
--mapper s3://......./mapper.py \
--reducer s3://....../code/reducer.py

and got the same error message:   **Error: {"__type":"ValidationException","message":"InstanceProfile is required for creating cluster."}**

I might be missing some sthing!

any help is welcomed
