### ISSUE TITLE
Migration to 5.0.2 (from 4.0.5) causes `.run` to not return jobflow_id

### ISSUE THREAD

**Issue by slpsys** [rslifka/elasticity#86]
Hey there,

After testing the migration to the gem version of 5.0.2 from 4.x, we noticed that our `JobFlow` objects, while creating the underlying EMR job perfectly fine, the jobflow itself does not contain any jobflow id (the objects have an empty string), so subsequent calls (like to `status`) fail.

I fired up a local instance and stuck a `pry` session into the local gem right [here](https://github.com/rslifka/elasticity/blob/v5.0.2/lib/elasticity/emr.rb#L192), where the AWS API call returns, and noticed that what we're getting back is a stringified, unnamespaced JSON hash, _not_ a namespaced SOAP/XML RunJobFlowResponse like the [spec seems to indicate the code is looking for](https://github.com/rslifka/elasticity/blob/v5.0.2/spec/lib/elasticity/emr_spec.rb#L256-L263):

        From: /Users/marc/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/elasticity-5.0.2/lib/elasticity/emr.rb @ line 193 Elasticity::EMR#run_job_flow:

            187: def run_job_flow(job_flow_config)
            188:   params = {
            189:     :operation => 'RunJobFlow',
            190:   }.merge!(job_flow_config)
            191:   aws_result = @aws_request.submit(params)
            192:   require 'pry'
         => 193:   binding.pry
            194:   yield aws_result if block_given?
            195:   xml_doc = Nokogiri::XML(aws_result)
            196:   xml_doc.remove_namespaces!
            197:   xml_doc.xpath('/RunJobFlowResponse/RunJobFlowResult/JobFlowId').text
            198: end

        [1] pry(#<Elasticity::EMR>)> aws_result
        => "{\"JobFlowId\":\"j-3IAYJEMI1043Y\"}"

Any idea what's going on here? I noticed that there's a `yield`/`block_given?`, which almost seems like the issue would go away as-is by calling as:

    run_job_flow(config) { |result| JSON.parse(result)["JobFlowId"] }

but that's obviously super brittle. Any idea what's going on here / suggestions?

**Comment by rslifka** [comment]
Interestingly, the [AWS docs](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_RunJobFlow.html) seem to disagree with themselves :)

```
The following element is returned in a structure named RunJobFlowResult.
```

...and then the sample response, with nary a `RunJobFlowResult` to be found :)

```
HTTP/1.1 200 OK
x-amzn-RequestId: a4406d6b-ed92-11e2-9787-192218ecb460
Content-Type: application/x-amz-json-1.1
Content-Length: 31
Date: Mon, 15 Jul 2013 21:08:05 GMT

{"JobFlowId": "j-ZKIY4CKQRX72"}
```

I'm sure it worked like that at some point, hence the structure in the spec.  I'll keep that code around if they decide to revert it.

**Comment by rslifka** [comment]
Fixed as of 3b690ca55526c8417688ac992a83dd62cbcdc2ed

**Comment by rslifka** [comment]
5.0.3 released

**Comment by slpsys** [comment]
Whoa, awesome! Thanks, Rob. :beers:
