### ISSUE TITLE
Use ListClusters/DescribeCluster instead of DescribeJobFlows

### ISSUE THREAD

**Issue by alexanderdean** [rslifka/elasticity#87]
Companion ticket to https://github.com/Yelp/mrjob/issues/876

**Comment by alexanderdean** [comment]
To provide a bit more info on this: our testing suggests that the API (which has been deprecated for a while) has been grandfathered on existing AWS accounts, but any AWS accounts which haven't yet run an EMR cluster are finding that the API has been completely removed. We experienced this setting up a new Snowplow customer.

**Comment by rslifka** [comment]
Looks like an [extensive set of changes](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html).

**Comment by alexanderdean** [comment]
Unfortunately yes!

**Comment by rslifka** [comment]
They've quietly changed nearly every API to return JSON instead of XML, which is terrific.  Would have saved a heck of a lot of time over the years ;)

**Comment by alexanderdean** [comment]
Indeed!

**Comment by rslifka** [comment]
Closing in favour of separate issues for each call in 6.0.  Thank you sir, for the heads up!

**Comment by slpsys** [comment]
haha, I just noticed this last night, as well.
