### ISSUE TITLE
Add support for API:DescribeCluster

### ISSUE THREAD

**Issue by rslifka** [rslifka/elasticity#97]
http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeCluster.html

**Comment by alexanderdean** [comment]
Hey @rslifka - can we help on some of these tickets? If you can think of a way of parcelling up the work so that we can help out, let us know, we'd be happy to...

**Comment by rslifka** [comment]
Fixed as of fa077cb63fdd64a9e537f99dcd882856feaf71d7

**Comment by rslifka** [comment]
Sure thing @alexanderdean.  The trick is how that gets exposed through the niceties of something like a `JobFlowStatus` and `JobFlowStatusStep` given the new APIs.  Still having a think through that :smile: 

Will send you a note momentarily.

**Comment by alexanderdean** [comment]
Cheers Rob!
